/*
Andrew R. Courtemanche 2020/12
*/

#ifndef ARCOS_CONFIG_GUARD
#define ARCOS_CONFIG_GUARD

#ifndef __MSP430FR6989__
    #error No supported microcontroller detected.
#endif

#ifndef ARCOS_CONFIG_TIMESLICE_MICROSECONDS
    #define ARCOS_CONFIG_TIMESLICE_MICROSECONDS (1000) //1ms //UNUSED
#endif
#ifndef ARCOS_CONFIG_PROC_COUNT_MAX
    #define ARCOS_CONFIG_PROC_COUNT_MAX (8)
#endif
#ifndef ARCOS_CONFIG_PROC_STACK_SIZE_MAX
    #define ARCOS_CONFIG_PROC_STACK_SIZE_MAX (1024)
#endif

#ifdef __MSP430FR6989__
    #define ARCOS_CONFIG_RAM_SIZE (2048)

    #define ARCOS_CONFIG_KERNEL_SIZE_STACK (512)

    #define ARCOS_CONFIG_REG_COUNT (16)
    #define ARCOS_CONFIG_REG_SIZE (2)

    #define ARCOS_CONFIG_CLOCK_SRC_FREQ_LFXT (32768)
    #define ARCOS_CONFIG_CLOCK_SRC_FREQ_HFXT (0)
    #define ARCOS_CONFIG_CLOCK_SRC_FREQ_VLO (10000)
    #define ARCOS_CONFIG_CLOCK_SRC_FREQ_MOD (5000000)
    #define ARCOS_CONFIG_CLOCK_SRC_FREQ_LFMOD (ARCOS_CONFIG_CLOCK_FREQ_MOD/128)
#endif

#endif //end ARCOS_CONFIG_GUARD
